name = "DDiL"
version = "0.1.0"
keywords = ["data structures"]
defaultTargets = ["BDD", "ZDD"]
testDriver = "test1"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.19.0-rc3"

[[lean_lib]]
name = "BDD"

[[lean_lib]]
name = "ZDD"

[[lean_lib]]
name = "Common"

[[lean_lib]]
name = "Graph"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "TestNumberOfPaths"

[[lean_exe]]
name = "test2"
root = "TestNumberOfPaths.Driver"

[[lean_exe]]
name = "test1"
root = "Test.driver"
